---
title: "Alcohol Effects on Oviposition of L. Sericata"
author: "HHC"
date: "2018-12-19"
output: 
  prettydoc::html_pretty:
    theme: tactile
    toc: true

---

# Literature

# Rationale

# Methods & Materials
## Preliminary
1. Defrost (30g) pre-weighed and pre-blended liver from freezer for about one hour. Do not microwave as that will cook the liver.

2. Defrost blood -- this may take long so fill a beaker with water and place the vial of blood in the beaker. Then put beaker on a hot plate and turn the setting to hiigh (10). It takes about 30 min for the blood to become liquid again. 

3. As everything is defrosting, take aluminum foil and make a little separation ledge to separate the blood and liver in the dish. To make this ledge, take about a 6in x 6in square of foil. Fold in half and then fold the two sides so you have an accordian-like fold. Then insert the ledge to a clean petri dish bottom (This is hard to describe so I'll trust you can rig something that's usable. It doesn't have to be exact.)

4. Add liver to one side of the petri dish and add 5mL of blood to the other side of the petri dish.

5. Set up the treatments as follows:
    - Control - blood + liver; do not add anything
    - Acetic Acid ONLY - 40uL of pure acetic acid to LIVER side; mix well into liver. Do not add anything to the blood
    - Ethanol ONLY - 40uL of pure Ethanol to BLOOD side; mix well into blood Do not add anything to the liver
    - Acetic Acid + Ethanol - 40uL of acetic acid to the liver and 40uL of Ethanol to blood. Mix well
    
6. Place the treatments into the 4 corners of the cage. You can leave it in the cage for up to 15 hours and at least 8 hours. Preferably longer to allow more oviposition. Take note of which corner each treatment was in. 


# Protocol & Setup

## Cage 
1. Put together 12" x 12" meshed cages.
2. Supply with 4-5 sugar cubes and a 50mL Erlenmeyer flask filled with water and place a sponge to close the opening.

## Rearing
1. Please refer to [Adult Fly Room > Extraction](https://hannahhchu.github.io/2018-12-13_gen_insect_rearing.html#extraction) and [Dark Room > Making Jars](https://hannahhchu.github.io/2018-12-13_gen_insect_rearing.html#making-jars)
2. When larvae begin to pupate, place ~5 pupae into petri dishes and tape down the petry dish cap.
3. Check every 24 hours until fly emergence.
4. Place petri dishes with emerged flies into cages keeping track of how many [females and males](https://user-images.githubusercontent.com/26017826/50249572-65e0cb80-03ac-11e9-89da-29173014728d.png) are in each group -- (this experiment will use 50F, 25M)
5. Remove the additional male and female flies from the cage.
6. Allow 3-7 days for virgin flies to mate. 

## Experimental

1. Obtain the needed number of clear, plastic storage boxes
2. Insert a PVC tube (with air filter?) into the storage box.
3. Place cage with mated flies into the storage box.
4. Place test samples into cage and close the storage box lid. 
5. Observe oviposition behavior of female flies. Check every 15 minutes for 2 hours. 

*Note: Please find template data sheets [here]()*

# Results

